// Independently maintained disposition for every concrete structured API route.
export const mcpExclusionReasons = [
  'account_deletion',
  'account_registration_or_verification',
  'authentication_or_account_linking',
  'bulk_email_control',
  'bulk_file_import',
  'mcp_token_management',
  'public_mutation',
  'raw_binary_transfer',
  'raw_binary_upload',
  'system_integration_control',
  'webhook_or_system_consumer'
] as const

export type McpExclusionReason = typeof mcpExclusionReasons[number]
export type McpEligibilityEntry
  = | { route: string, disposition: 'include' }
    | { route: string, disposition: 'exclude', reason: McpExclusionReason }

export const mcpEligibilityManifest = [
  { route: 'account.delete.ts', disposition: 'exclude', reason: 'account_deletion' },
  { route: 'account.patch.ts', disposition: 'include' },
  { route: 'account/email-verification.post.ts', disposition: 'exclude', reason: 'account_registration_or_verification' },
  { route: 'account/events.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/certificates.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/entry.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/feedback.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/gallery.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/judging.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/judging/assignments/[assignmentId].get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/operations.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/participants.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/prizes.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/rosters.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/settings.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/submissions.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/teams.get.ts', disposition: 'include' },
  { route: 'account/events/[slug]/workspace.get.ts', disposition: 'include' },
  { route: 'account/judging.get.ts', disposition: 'include' },
  { route: 'account/overview.get.ts', disposition: 'include' },
  { route: 'account/staff-workspace.get.ts', disposition: 'include' },
  { route: 'account/mcp-tokens/[tokenId].delete.ts', disposition: 'exclude', reason: 'mcp_token_management' },
  { route: 'account/mcp-tokens/index.get.ts', disposition: 'exclude', reason: 'mcp_token_management' },
  { route: 'account/mcp-tokens/index.post.ts', disposition: 'exclude', reason: 'mcp_token_management' },
  { route: 'account/profile-icon.delete.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'account/profile-icon.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'account/profile-icon.post.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'account/registration.post.ts', disposition: 'exclude', reason: 'account_registration_or_verification' },
  { route: 'admin/events/[eventId]/actions/backfill-luma-emails.post.ts', disposition: 'exclude', reason: 'system_integration_control' },
  { route: 'audit/index.get.ts', disposition: 'include' },
  { route: 'event-organizers/[userId].delete.ts', disposition: 'include' },
  { route: 'event-organizers/[userId].put.ts', disposition: 'include' },
  { route: 'event-organizers/candidates/index.get.ts', disposition: 'include' },
  { route: 'event-organizers/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/advance-pitch-presentation.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/announce-winners.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/complete.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/hide.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/open-registration.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/open-submission.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/start-blind-review.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/start-final-deliberation.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/start-judging-preparation.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/start-pitch-review.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/start-pitch.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/start-shortlist.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/actions/unhide.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/admin/credits/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/[applicationId]/actions/approve.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/[applicationId]/actions/override-check-in.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/[applicationId]/actions/reject.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/[applicationId]/actions/set-certificate-revocation.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/[applicationId]/actions/undo-withdrawal.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/[applicationId]/actions/withdraw.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/actions/apply-staged-decisions.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/actions/send-certificate-emails.post.ts', disposition: 'exclude', reason: 'bulk_email_control' },
  { route: 'events/[eventId]/applications/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/index.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/me.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/me/actions/select-track.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/me/actions/set-certificate-visibility.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/me/actions/verify-luma-email.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/applications/me/actions/withdraw.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/audit/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/credits/[creditId].delete.ts', disposition: 'include' },
  { route: 'events/[eventId]/credits/[creditId].patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/credits/[creditId]/actions/claim.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/credits/[creditId]/import.post.ts', disposition: 'exclude', reason: 'bulk_file_import' },
  { route: 'events/[eventId]/credits/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/credits/index.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/evaluation-criteria/[criterionId].delete.ts', disposition: 'include' },
  { route: 'events/[eventId]/evaluation-criteria/[criterionId].patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/evaluation-criteria/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/evaluation-criteria/index.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/feedback/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/final-deliberation/actions/reorder.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/final-deliberation/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/images/background.delete.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'events/[eventId]/images/background.post.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'events/[eventId]/images/banner.delete.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'events/[eventId]/images/banner.post.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'events/[eventId]/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/index.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/judges/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/actions/complete.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/actions/force-skip.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/actions/mark-ineligible.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/actions/reassign.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/actions/revert-ineligibility.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/actions/skip.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/actions/start.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/[assignmentId]/index.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/assignments/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/judging/summary.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/leaderboard/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/luma/actions/retry-configuration.post.ts', disposition: 'exclude', reason: 'system_integration_control' },
  { route: 'events/[eventId]/no-submission-teams/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/photos/[photoId].delete.ts', disposition: 'include' },
  { route: 'events/[eventId]/photos/[photoId]/highlight.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/photos/[photoId]/image.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'events/[eventId]/photos/[photoId]/public-visibility.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/photos/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/photos/index.post.ts', disposition: 'exclude', reason: 'raw_binary_upload' },
  { route: 'events/[eventId]/prize-redemptions/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/prizes/[prizeId].delete.ts', disposition: 'include' },
  { route: 'events/[eventId]/prizes/[prizeId].patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/prizes/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/prizes/index.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/published-projects/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/rank/me.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/roles/[userId].delete.ts', disposition: 'include' },
  { route: 'events/[eventId]/roles/[userId].patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/roles/[userId].put.ts', disposition: 'include' },
  { route: 'events/[eventId]/roles/candidates/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/roles/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/shortlist/actions/select-finalists.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/shortlist/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/simplified-claiming/attendees/import-check-ins.post.ts', disposition: 'exclude', reason: 'system_integration_control' },
  { route: 'events/[eventId]/simplified-claiming/attendees/import.post.ts', disposition: 'exclude', reason: 'bulk_file_import' },
  { route: 'events/[eventId]/simplified-claiming/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/simplified-claiming/rewards/[creditId].patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/simplified-claiming/rewards/import.post.ts', disposition: 'exclude', reason: 'bulk_file_import' },
  { route: 'events/[eventId]/staff/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/submissions/summary.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/[proposalId]/actions/accept.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/[proposalId]/actions/reject.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/[proposalId]/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/me.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/me.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/me.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/me/actions/revise.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/me/actions/submit.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/talk-proposals/me/actions/withdraw.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/team-join-requests/[requestId]/actions/approve.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/team-join-requests/[requestId]/actions/cancel.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/team-join-requests/[requestId]/actions/reject.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/team-join-requests/index.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/actions/leave.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/index.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/join-policy.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/join-requests/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/members/[userId]/actions/make-admin.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/members/[userId]/actions/remove.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/submission/actions/admin-withdraw.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/submission/actions/disqualify.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/submission/actions/submit.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/submission/actions/withdraw.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/submission/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/submission/index.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/submission/index.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/[teamId]/submission/public-visibility.patch.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/index.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/index.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/teams/submission-monitor.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/terms/[documentType]/actions/set-current.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/terms/[documentType]/versions.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/terms/[documentType]/versions.post.ts', disposition: 'include' },
  { route: 'events/[eventId]/terms/current.get.ts', disposition: 'include' },
  { route: 'events/[eventId]/winners/index.get.ts', disposition: 'include' },
  { route: 'events/builder/analyze.post.ts', disposition: 'include' },
  { route: 'events/builder/catalog.get.ts', disposition: 'include' },
  { route: 'events/index.get.ts', disposition: 'include' },
  { route: 'events/index.post.ts', disposition: 'include' },
  { route: 'events/participation.get.ts', disposition: 'include' },
  { route: 'events/slug/[slug]/index.get.ts', disposition: 'include' },
  { route: 'events/slug/[slug]/simplified-claim.get.ts', disposition: 'include' },
  { route: 'events/slug/[slug]/simplified-claim/actions/redeem.post.ts', disposition: 'include' },
  { route: 'platform-admins/[userId].delete.ts', disposition: 'include' },
  { route: 'platform-admins/[userId].put.ts', disposition: 'include' },
  { route: 'platform-admins/candidates/index.get.ts', disposition: 'include' },
  { route: 'platform-admins/index.get.ts', disposition: 'include' },
  { route: 'platform-document-acceptances.post.ts', disposition: 'include' },
  { route: 'platform-documents/[documentType]/versions.get.ts', disposition: 'include' },
  { route: 'platform-documents/[documentType]/versions.post.ts', disposition: 'include' },
  { route: 'platform-documents/current.get.ts', disposition: 'include' },
  { route: 'platform-legal-settings/current.get.ts', disposition: 'include' },
  { route: 'platform-legal-settings/current.patch.ts', disposition: 'include' },
  { route: 'platform-settings/current.get.ts', disposition: 'include' },
  { route: 'platform-settings/event-default-background-image.delete.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'platform-settings/event-default-background-image.post.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'prize-redemptions/[redemptionId]/actions/redeem.post.ts', disposition: 'include' },
  { route: 'prize-redemptions/me.get.ts', disposition: 'include' },
  { route: 'prize-redemptions/workspace.get.ts', disposition: 'include' },
  { route: 'public/events/[slug]/evaluation-criteria/index.get.ts', disposition: 'include' },
  { route: 'public/events/[slug]/feedback.post.ts', disposition: 'exclude', reason: 'public_mutation' },
  { route: 'public/events/[slug]/images/background.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'public/events/[slug]/images/banner.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'public/events/[slug]/index.get.ts', disposition: 'include' },
  { route: 'public/events/[slug]/luma/webhooks.post.ts', disposition: 'exclude', reason: 'webhook_or_system_consumer' },
  { route: 'public/events/[slug]/participants/[userId]/certificate.get.ts', disposition: 'include' },
  { route: 'public/events/[slug]/participants/[userId]/certificate.pdf.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'public/events/[slug]/participants/[userId]/certificate.png.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'public/events/[slug]/photos/[photoId]/image.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'public/events/[slug]/photos/index.get.ts', disposition: 'include' },
  { route: 'public/events/[slug]/prizes/index.get.ts', disposition: 'include' },
  { route: 'public/events/[slug]/published-projects/[userId]/profile-icon.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'public/events/[slug]/published-projects/index.get.ts', disposition: 'include' },
  { route: 'public/events/[slug]/winners/[userId]/profile-icon.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'public/events/[slug]/winners/index.get.ts', disposition: 'include' },
  { route: 'public/events/index.get.ts', disposition: 'include' },
  { route: 'public/imprint-contact.post.ts', disposition: 'exclude', reason: 'public_mutation' },
  { route: 'public/platform/event-default-background-image.get.ts', disposition: 'exclude', reason: 'raw_binary_transfer' },
  { route: 'session.get.ts', disposition: 'exclude', reason: 'authentication_or_account_linking' }
] as const satisfies readonly McpEligibilityEntry[]
