import { describe, expect, it } from 'vitest'
import { getTableColumns, getTableName } from 'drizzle-orm'
import { getTableConfig } from 'drizzle-orm/sqlite-core'

import {
  auditLogs,
  eventAttendeeEligibilities,
  eventCreditCodes,
  eventCreditOffers,
  eventFeedback,
  eventPhotos,
  eventRoleAssignments,
  eventTracks,
  events,
  judgeAssignments,
  platformSettings,
  prizeEligibilitySnapshots,
  prizeRedemptions,
  prizes,
  submissions,
  teamJoinRequests,
  userAuthIdentities,
  userApplications,
  users
} from '../../../../server/database/schema'

describe('shared schema foundation', () => {
  it('stores the primary Auth0 subject on the user record and linked subjects in identity rows', () => {
    const columns = getTableColumns(users)
    const identityColumns = getTableColumns(userAuthIdentities)

    expect(getTableName(users)).toBe('users')
    expect(columns.auth0Subject.name).toBe('auth0_subject')
    expect(getTableName(userAuthIdentities)).toBe('user_auth_identities')
    expect(identityColumns.auth0Subject.name).toBe('auth0_subject')
    expect(identityColumns.userId.name).toBe('user_id')
    expect(columns.firstName.name).toBe('first_name')
    expect(columns.familyName.name).toBe('family_name')
    expect(columns.company.name).toBe('company')
    expect(columns.bio.name).toBe('bio')
    expect(columns.isEventOrganizer.name).toBe('is_event_organizer')
    expect(columns.profileIconUpdatedAt.name).toBe('profile_icon_updated_at')
    expect(columns.profileIconObjectKey.name).toBe('profile_icon_object_key')
    expect(columns.profileIconRevision.name).toBe('profile_icon_revision')
  })

  it('defines the documented partial unique indexes', () => {
    const userIndexes = getTableConfig(users).indexes.map(index => index.config.name)
    const userAuthIdentityIndexes = getTableConfig(userAuthIdentities).indexes.map(index => index.config.name)
    const joinRequestIndexes = getTableConfig(teamJoinRequests).indexes.map(index => index.config.name)
    const trackIndexes = getTableConfig(eventTracks).indexes.map(index => index.config.name)
    const feedbackIndexes = getTableConfig(eventFeedback).indexes.map(index => index.config.name)
    const photoIndexes = getTableConfig(eventPhotos).indexes.map(index => index.config.name)
    const submissionIndexes = getTableConfig(submissions).indexes.map(index => index.config.name)
    const assignmentIndexes = getTableConfig(judgeAssignments).indexes.map(index => index.config.name)
    const creditOfferIndexes = getTableConfig(eventCreditOffers).indexes.map(index => index.config.name)
    const creditCodeIndexes = getTableConfig(eventCreditCodes).indexes.map(index => index.config.name)
    const attendeeEligibilityIndexes = getTableConfig(eventAttendeeEligibilities).indexes.map(index => index.config.name)
    const prizeEligibilitySnapshotIndexes = getTableConfig(prizeEligibilitySnapshots).indexes.map(index => index.config.name)
    const prizeRedemptionIndexes = getTableConfig(prizeRedemptions).indexes.map(index => index.config.name)

    expect(userIndexes).toContain('users_auth0_subject_active_idx')
    expect(userIndexes).toContain('users_email_active_idx')
    expect(userAuthIdentityIndexes).toContain('user_auth_identities_auth0_subject_idx')
    expect(joinRequestIndexes).toContain('team_join_requests_pending_team_user_idx')
    expect(trackIndexes).toContain('event_tracks_event_display_order_idx')
    expect(trackIndexes).toContain('event_tracks_event_idx')
    expect(feedbackIndexes).toContain('event_feedback_event_created_idx')
    expect(photoIndexes).toContain('event_photos_event_created_idx')
    expect(photoIndexes).toContain('event_photos_uploaded_by_idx')
    expect(submissionIndexes).toContain('submissions_active_team_idx')
    expect(submissionIndexes).toContain('submissions_track_idx')
    expect(assignmentIndexes).toContain('judge_assignments_active_blind_submission_slot_idx')
    expect(assignmentIndexes).toContain('judge_assignments_pitch_submission_judge_idx')
    expect(assignmentIndexes).toContain('judge_assignments_event_stage_status_judge_idx')
    expect(creditOfferIndexes).toContain('event_credit_offers_event_display_order_idx')
    expect(creditOfferIndexes).toContain('event_credit_offers_redirect_event_idx')
    expect(creditCodeIndexes).toContain('event_credit_codes_offer_claim_state_idx')
    expect(creditCodeIndexes).toContain('event_credit_codes_offer_claimed_user_idx')
    expect(creditCodeIndexes).toContain('event_credit_codes_claimed_attendee_eligibility_idx')
    expect(attendeeEligibilityIndexes).toContain('event_attendee_eligibilities_event_email_idx')
    expect(attendeeEligibilityIndexes).toContain('event_attendee_eligibilities_event_created_idx')
    expect(prizeEligibilitySnapshotIndexes).toContain('prize_eligibility_snapshots_event_user_team_idx')
    expect(prizeEligibilitySnapshotIndexes).toContain('prize_eligibility_snapshots_event_team_user_idx')
    expect(prizeRedemptionIndexes).toContain('prize_redemptions_pending_user_created_idx')
    expect(prizeRedemptionIndexes).toContain('prize_redemptions_pending_team_created_idx')
  })

  it('defines schedule and entity checks on shared tables', () => {
    const eventColumns = getTableColumns(events)
    const creditOfferColumns = getTableColumns(eventCreditOffers)
    const creditCodeColumns = getTableColumns(eventCreditCodes)
    const trackColumns = getTableColumns(eventTracks)
    const feedbackColumns = getTableColumns(eventFeedback)
    const photoColumns = getTableColumns(eventPhotos)
    const roleAssignmentColumns = getTableColumns(eventRoleAssignments)
    const applicationColumns = getTableColumns(userApplications)
    const prizeColumns = getTableColumns(prizes)
    const submissionColumns = getTableColumns(submissions)
    const prizeChecks = getTableConfig(prizes).checks.map(checkItem => checkItem.name)
    const eventChecks = getTableConfig(events).checks.map(checkItem => checkItem.name)
    const roleAssignmentChecks = getTableConfig(eventRoleAssignments).checks.map(checkItem => checkItem.name)
    const feedbackChecks = getTableConfig(eventFeedback).checks.map(checkItem => checkItem.name)
    const photoChecks = getTableConfig(eventPhotos).checks.map(checkItem => checkItem.name)
    const auditIndexes = getTableConfig(auditLogs).indexes.map(index => index.config.name)
    const platformSettingsColumns = getTableColumns(platformSettings)
    const platformSettingsChecks = getTableConfig(platformSettings).checks.map(checkItem => checkItem.name)

    expect(eventColumns.lumaEventUrl.name).toBe('luma_event_url')
    expect(eventColumns.discordServerUrl.name).toBe('discord_server_url')
    expect(eventColumns.slidesUrl.name).toBe('slides_url')
    expect(eventColumns.lumaEventApiId.name).toBe('luma_event_api_id')
    expect(eventColumns.lumaApiKey.name).toBe('luma_api_key')
    expect(eventColumns.lumaWebhookId.name).toBe('luma_webhook_id')
    expect(eventColumns.lumaWebhookSecret.name).toBe('luma_webhook_secret')
    expect(eventColumns.lumaWebhookStatus.name).toBe('luma_webhook_status')
    expect(eventColumns.lumaWebhookError.name).toBe('luma_webhook_error')
    expect(eventColumns.lumaWebhookRegisteredAt.name).toBe('luma_webhook_registered_at')
    expect(eventColumns.agendaItemsJson.name).toBe('agenda_items_json')
    expect(eventColumns.country.name).toBe('country')
    expect(eventColumns.inPersonEvent.name).toBe('in_person_event')
    expect(eventColumns.participantsLimit.name).toBe('participants_limit')
    expect(eventColumns.autoApproveApplications.name).toBe('auto_approve_applications')
    expect(eventColumns.simplifiedClaimingEnabled.name).toBe('simplified_claiming_enabled')
    expect(eventColumns.shortlistFinalistCount.name).toBe('shortlist_finalist_count')
    expect(eventColumns.pitchFinalistSubmissionIdsJson.name).toBe('pitch_finalist_submission_ids_json')
    expect(eventColumns.activePitchPresentationSubmissionId.name).toBe('active_pitch_presentation_submission_id')
    expect(eventColumns.pitchPresentationsCompletedAt.name).toBe('pitch_presentations_completed_at')
    expect(eventColumns.finalRankingSubmissionIdsJson.name).toBe('final_ranking_submission_ids_json')
    expect(eventColumns.applicationXProfileVisible.name).toBe('application_x_profile_visible')
    expect(eventColumns.applicationLinkedinProfileVisible.name).toBe('application_linkedin_profile_visible')
    expect(eventColumns.applicationGithubProfileVisible.name).toBe('application_github_profile_visible')
    expect(eventColumns.applicationChatgptEmailVisible.name).toBe('application_chatgpt_email_visible')
    expect(eventColumns.applicationOpenaiOrgIdVisible.name).toBe('application_openai_org_id_visible')
    expect(eventColumns.applicationLumaEmailVisible.name).toBe('application_luma_email_visible')
    expect(eventColumns.applicationWhyThisEventVisible.name).toBe('application_why_this_event_visible')
    expect(eventColumns.applicationProofOfExecutionVisible.name).toBe('application_proof_of_execution_visible')
    expect(eventColumns.applicationTeamIntentVisible.name).toBe('application_team_intent_visible')
    expect(eventColumns.applicationAiKnowledgeVisible.name).toBe('application_ai_knowledge_visible')
    expect(eventColumns.requireWhyThisEvent.name).toBe('require_why_this_event')
    expect(eventColumns.requireProofOfExecution.name).toBe('require_proof_of_execution')
    expect(eventColumns.requireTeamIntent.name).toBe('require_team_intent')
    expect(eventColumns.requireAiKnowledge.name).toBe('require_ai_knowledge')
    expect(eventColumns.requireSubmissionSummary.name).toBe('require_submission_summary')
    expect(eventColumns.requireSubmissionRepositoryUrl.name).toBe('require_submission_repository_url')
    expect(eventColumns.requireSubmissionDemoUrl.name).toBe('require_submission_demo_url')
    expect(trackColumns.eventId.name).toBe('event_id')
    expect(trackColumns.shortDescription.name).toBe('short_description')
    expect(trackColumns.fullDescription.name).toBe('full_description')
    expect(trackColumns.staffInstructions.name).toBe('staff_instructions')
    expect(trackColumns.resourcesJson.name).toBe('resources_json')
    expect(trackColumns.displayOrder.name).toBe('display_order')
    expect(feedbackColumns.eventId.name).toBe('event_id')
    expect(feedbackColumns.foodRating.name).toBe('food_rating')
    expect(feedbackColumns.participantsCommunityRating.name).toBe('participants_community_rating')
    expect(feedbackColumns.communicationBeforeRating.name).toBe('communication_before_rating')
    expect(feedbackColumns.communicationDuringRating.name).toBe('communication_during_rating')
    expect(feedbackColumns.rulesFairnessRating.name).toBe('rules_fairness_rating')
    expect(feedbackColumns.safetyAccessibilityInclusionRating.name).toBe('safety_accessibility_inclusion_rating')
    expect(feedbackColumns.comment.name).toBe('comment')
    expect(photoColumns.fileName.name).toBe('file_name')
    expect(photoColumns.objectKey.name).toBe('object_key')
    expect(photoColumns.imageRevision.name).toBe('image_revision')
    expect(photoColumns.isPubliclyVisible.name).toBe('is_publicly_visible')
    expect(photoColumns.isHighlighted.name).toBe('is_highlighted')
    expect(photoColumns.contentType.name).toBe('content_type')
    expect(photoColumns.uploadedByUserId.name).toBe('uploaded_by_user_id')
    expect(roleAssignmentColumns.isStaff.name).toBe('is_staff')
    expect(roleAssignmentColumns.staffTrackId.name).toBe('staff_track_id')
    expect(applicationColumns.preApprovalStatus.name).toBe('pre_approval_status')
    expect(applicationColumns.lumaSyncStatus.name).toBe('luma_sync_status')
    expect(applicationColumns.checkedInAt.name).toBe('checked_in_at')
    expect(applicationColumns.checkInSource.name).toBe('check_in_source')
    expect(applicationColumns.checkInOverrideStatus.name).toBe('check_in_override_status')
    expect(applicationColumns.checkInOverrideAt.name).toBe('check_in_override_at')
    expect(applicationColumns.checkInOverrideByUserId.name).toBe('check_in_override_by_user_id')
    expect(applicationColumns.certificateHiddenAt.name).toBe('certificate_hidden_at')
    expect(applicationColumns.certificateRevokedAt.name).toBe('certificate_revoked_at')
    expect(applicationColumns.certificateRevokedByUserId.name).toBe('certificate_revoked_by_user_id')
    expect(applicationColumns.selectedTrackId.name).toBe('selected_track_id')
    expect(creditOfferColumns.eventId.name).toBe('event_id')
    expect(creditOfferColumns.simplifiedClaimingOnly.name).toBe('simplified_claiming_only')
    expect(creditOfferColumns.displayOrder.name).toBe('display_order')
    expect(creditCodeColumns.creditOfferId.name).toBe('credit_offer_id')
    expect(creditCodeColumns.claimedByUserId.name).toBe('claimed_by_user_id')
    expect(creditCodeColumns.claimedAttendeeEligibilityId.name).toBe('claimed_attendee_eligibility_id')
    expect(prizeColumns.displayOrder.name).toBe('display_order')
    expect(submissionColumns.trackId.name).toBe('track_id')
    expect(getTableConfig(userApplications).indexes.map(index => index.config.name)).toContain('user_applications_event_selected_track_idx')
    expect(getTableColumns(judgeAssignments).reviewStage.name).toBe('review_stage')
    expect(getTableColumns(judgeAssignments).blindReviewSlot.name).toBe('blind_review_slot')
    expect(getTableColumns(judgeAssignments).pitchScore.name).toBe('pitch_score')
    expect(getTableColumns(judgeAssignments).pitchComment.name).toBe('pitch_comment')
    expect(prizeChecks).toContain('prizes_rank_order_check')
    expect(eventChecks).toContain('events_max_team_members_check')
    expect(eventChecks).toContain('events_participants_limit_check')
    expect(eventChecks).toContain('events_schedule_order_check')
    expect(eventChecks).toContain('events_luma_webhook_status_check')
    expect(getTableConfig(events).indexes.map(index => index.config.name)).toContain('events_luma_event_api_id_idx')
    expect(roleAssignmentChecks).toContain('event_role_assignments_judge_pool_check')
    expect(roleAssignmentChecks).toContain('event_role_assignments_staff_flag_check')
    expect(roleAssignmentChecks).toContain('event_role_assignments_staff_track_check')
    expect(feedbackChecks).toContain('event_feedback_food_rating_check')
    expect(feedbackChecks).toContain('event_feedback_safety_accessibility_inclusion_rating_check')
    expect(photoChecks).toContain('event_photos_width_check')
    expect(photoChecks).toContain('event_photos_height_check')
    expect(auditIndexes).toContain('audit_logs_entity_idx')
    expect(auditIndexes).toContain('audit_logs_created_idx')
    expect(auditIndexes).toContain('audit_logs_entity_created_idx')
    expect(auditIndexes).toContain('audit_logs_metadata_event_created_idx')
    expect(getTableName(platformSettings)).toBe('platform_settings')
    expect(platformSettingsColumns.defaultEventBackgroundImageUrl.name).toBe('default_event_background_image_url')
    expect(platformSettingsColumns.defaultEventBackgroundImageObjectKey.name).toBe('default_event_background_image_object_key')
    expect(platformSettingsColumns.defaultEventBackgroundImageRevision.name).toBe('default_event_background_image_revision')
    expect(getTableColumns(events).backgroundImageObjectKey.name).toBe('background_image_object_key')
    expect(getTableColumns(events).backgroundImageRevision.name).toBe('background_image_revision')
    expect(getTableColumns(events).bannerImageObjectKey.name).toBe('banner_image_object_key')
    expect(getTableColumns(events).bannerImageRevision.name).toBe('banner_image_revision')
    expect(getTableColumns(events).publicContentRevision.name).toBe('public_content_revision')
    expect(platformSettingsChecks).toContain('platform_settings_singleton_id_check')
  })
})
